# Generated by Django 3.2.7 on 2021-09-29 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_alter_shoe_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made', to='shoes.manufacturer'),
        ),
    ]
